BASE_URL="https://data.fixer.io/api"
FREE_USER_ACCESS_KEY="7e11b9513983c180bbe22d05705b12c5"
BASIC_USER_ACCESS_KEY=""
PROFESSIONAL_USER_ACCESS_KEY=""

#APIEndpoints
GET_CURRENCIES="/symbols"
GET_LATEST="/latest"
GET_CONVERT="/convert"

DELAY_BETWEEN_REQUESTS_SECONDS=10

